#:schema node_modules/wrangler/config-schema.json
name = "thatskylink"
main = "source/index.ts"
compatibility_date = "2025-09-04"
compatibility_flags = ["nodejs_als"]
workers_dev = false
routes = [{ pattern = "thatsky.link", custom_domain = true }]

[observability]
enabled = true

[version_metadata]
binding = "CF_VERSION_METADATA"
